# Generated by Django 5.1.2 on 2024-11-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_confirmpassword_alter_contact_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='confirmpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
