# Generated by Django 5.1.2 on 2024-11-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_confirmpassword_alter_contact_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='confirmpassword',
        ),
    ]
