# Generated by Django 5.1.3 on 2024-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='course',
            field=models.CharField(default='unknown', max_length=122),
        ),
    ]
