# Generated by Django 5.1.4 on 2025-01-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
